services:
  - type: web
    name: strapi-backend
    env: node
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
    plan: free

  - type: web
    name: nextjs-frontend
    env: node
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
    plan: free